/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author DELL
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    private HomePage homePage;
    public Bill() {
        initComponents();
        setSize(300, 400);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    
    public Bill(HomePage homePage) {
        initComponents();
        setSize(300, 400);
        this.homePage = homePage;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    
    public Bill(HomePage homePage, String total, String date) {
        initComponents();
        setSize(300, 400);
        this.homePage = homePage;
        this.total.setText(total);
        this.date.setText(date);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                homePage.setEnabled(true);
                homePage.resetValue();
                setVisible(false);
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        exitbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Thanh toán thành công");
        jPanel10.add(jLabel6);

        getContentPane().add(jPanel10);

        jPanel20.setLayout(new java.awt.GridLayout(3, 2));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Thành tiền");
        jPanel20.add(jLabel8);

        total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel20.add(total);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Ngày");
        jPanel20.add(jLabel11);

        date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel20.add(date);

        getContentPane().add(jPanel20);

        exitbt.setText("Thoát");
        exitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtActionPerformed(evt);
            }
        });
        jPanel21.add(exitbt);

        getContentPane().add(jPanel21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtActionPerformed
        this.homePage.setEnabled(true);
        this.homePage.resetValue();
        this.setVisible(false);
    }//GEN-LAST:event_exitbtActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JButton exitbt;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
